// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tenli.Server.Data;

namespace Tenli.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190223214859_OrderLocation")]
    partial class OrderLocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Tenli.Server.Data.Models.ActiveSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicationUserId");

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("IPAddress");

                    b.Property<bool>("IsTerminated");

                    b.Property<DateTime>("LastRefreshDateTime");

                    b.Property<string>("Location");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("UserAgent");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ActiveSessions");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ApplicationRoles");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Hash");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsBanned");

                    b.Property<string>("LastName");

                    b.Property<int>("LoginAttempts");

                    b.Property<DateTime?>("LoginBannedUntilDateTime");

                    b.Property<string>("MiddleName");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.Property<string>("Phone");

                    b.Property<string>("PushNotificationsToken");

                    b.Property<byte[]>("Salt");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.Culture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Cultures");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.LocalizationResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<int>("CultureId");

                    b.Property<int?>("CurrencyId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.Property<int?>("OrderStatusId");

                    b.Property<int?>("ProductTypeId");

                    b.Property<int?>("SizeUnitId");

                    b.Property<string>("Value");

                    b.Property<int?>("VolumeUnitId");

                    b.Property<int?>("WeightUnitId");

                    b.HasKey("Id");

                    b.HasIndex("CultureId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SizeUnitId");

                    b.HasIndex("VolumeUnitId");

                    b.HasIndex("WeightUnitId");

                    b.ToTable("LocalizationResources");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<Point>("EndLocation")
                        .HasColumnType("geography")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<DateTime>("ExpectingDateTime");

                    b.Property<DateTime>("FinishingTime");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.Property<int>("OrderStatusId");

                    b.Property<Point>("StartLocation")
                        .HasColumnType("geography")
                        .HasAnnotation("Sqlite:Srid", 4326);

                    b.Property<DateTime>("TakingDateTime");

                    b.HasKey("Id");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderId");

                    b.Property<int>("ProductId");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<int?>("CurrencyId");

                    b.Property<int?>("Depth");

                    b.Property<string>("Description");

                    b.Property<int?>("Height");

                    b.Property<string>("Image");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.Property<int>("Price");

                    b.Property<int>("ProductTypeId");

                    b.Property<int?>("SizeUnitId");

                    b.Property<int?>("Volume");

                    b.Property<int?>("VolumeUnitId");

                    b.Property<int>("Weight");

                    b.Property<int>("WeightUnitId");

                    b.Property<int?>("Width");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SizeUnitId");

                    b.HasIndex("VolumeUnitId");

                    b.HasIndex("WeightUnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.SizeUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.HasKey("Id");

                    b.ToTable("SizeUnits");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.UserRole", b =>
                {
                    b.Property<int>("ApplicationRoleId");

                    b.Property<int>("ApplicationUserId");

                    b.HasKey("ApplicationRoleId", "ApplicationUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.VolumeUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.HasKey("Id");

                    b.ToTable("VolumeUnits");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.WeightUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDateTime");

                    b.Property<string>("CreationUser");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Key");

                    b.Property<DateTime>("ModificationDateTime");

                    b.Property<string>("ModificationUser");

                    b.HasKey("Id");

                    b.ToTable("WeightUnits");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.ActiveSession", b =>
                {
                    b.HasOne("Tenli.Server.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("ActiveSessions")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.LocalizationResource", b =>
                {
                    b.HasOne("Tenli.Server.Data.Models.Culture", "Culture")
                        .WithMany()
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tenli.Server.Data.Models.Currency")
                        .WithMany("Names")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Tenli.Server.Data.Models.OrderStatus", "OrederStatus")
                        .WithMany("Names")
                        .HasForeignKey("OrderStatusId");

                    b.HasOne("Tenli.Server.Data.Models.ProductType", "ProductType")
                        .WithMany("Names")
                        .HasForeignKey("ProductTypeId");

                    b.HasOne("Tenli.Server.Data.Models.SizeUnit")
                        .WithMany("Descriptions")
                        .HasForeignKey("SizeUnitId");

                    b.HasOne("Tenli.Server.Data.Models.VolumeUnit")
                        .WithMany("Descriptions")
                        .HasForeignKey("VolumeUnitId");

                    b.HasOne("Tenli.Server.Data.Models.WeightUnit")
                        .WithMany("Descriptions")
                        .HasForeignKey("WeightUnitId");
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.Order", b =>
                {
                    b.HasOne("Tenli.Server.Data.Models.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.OrderProduct", b =>
                {
                    b.HasOne("Tenli.Server.Data.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tenli.Server.Data.Models.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.Product", b =>
                {
                    b.HasOne("Tenli.Server.Data.Models.Currency", "Currency")
                        .WithMany("Products")
                        .HasForeignKey("CurrencyId");

                    b.HasOne("Tenli.Server.Data.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tenli.Server.Data.Models.SizeUnit", "SizeUnit")
                        .WithMany("Products")
                        .HasForeignKey("SizeUnitId");

                    b.HasOne("Tenli.Server.Data.Models.VolumeUnit", "VolumeUnit")
                        .WithMany("Products")
                        .HasForeignKey("VolumeUnitId");

                    b.HasOne("Tenli.Server.Data.Models.WeightUnit", "WeightUnit")
                        .WithMany("Products")
                        .HasForeignKey("WeightUnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tenli.Server.Data.Models.UserRole", b =>
                {
                    b.HasOne("Tenli.Server.Data.Models.ApplicationRole", "ApplicationRole")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tenli.Server.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
